src/UserBundle/Entity/User.php
<?php
// src/Acme/UserBundle/Entity/User.php

namespace UserBundle\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;
use FOS\MessageBundle\Model\ParticipantInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ORM\Table(name="fos_user")
 */
class User extends BaseUser implements ParticipantInterface
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

   // public function __construct()
   // {
     //   parent::__construct();
        // your own logic
  //  }
  
	   /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    public $pictureName;

    /**
     * @Assert\Image(maxSize="500k")
     */
    public $file;
    
    public function getWebPath()
    {
        return null === $this->pictureName ? null : $this->getUploadDir().'/'.$this->pictureName;
    }

    protected function getUploadRootDir()
    {
        // le chemin absolu du répertoire dans lequel sauvegarder les photos de profil
        return __DIR__.'/../../../web/'.$this->getUploadDir();
    }

    protected function getUploadDir()
    {
        // get rid of the __DIR__ so it doesn't screw when displaying uploaded doc/image in the view.
        return 'uploads/pictures';
    }
    
    public function uploadProfilePicture()
    {
        // Nous utilisons le nom de fichier original, donc il est dans la pratique 
        // nécessaire de le nettoyer pour éviter les problèmes de sécurité

        // move copie le fichier présent chez le client dans le répertoire indiqué.
        $this->file->move($this->getUploadRootDir(), $this->file->getClientOriginalName());

        // On sauvegarde le nom de fichier
        $this->pictureName = $this->file->getClientOriginalName();
        
        // La propriété file ne servira plus
        $this->file = null;
    }
}

src/UserBundle/Form/IdentityPictureType.php
<?php

namespace UserBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class IdentityPictureType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('file')
        ;
    }
    public function getName()
    {
        return 'userbundle_identitypicturetype';
    }
}

src/UserBundle/Controller/DefaultController.php
<?php

namespace UserBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use ProjectBundle\Entity\Project;
use ProjectBundle\Form\ProjectType;
use UserBundle\Entity\User;
use UserBundle\Form\IdentityPictureType;

class DefaultController extends Controller
{
    public function indexAction($name)
    {
        return $this->render('UserBundle:Default:index.html.twig', array('name' => $name));
    }


    public function paramAction(){

  

		return $this->render('UserBundle:Parameters:param.html.twig');

    }



     /**
     * @Route("/profil/{id}", name="profil_show")
     * @ParamConverter("user", class="UserBundle:User")
     * @Template()
     */
    public function showAction(User $user)
    {

        $em = $this -> getDoctrine() -> getEntityManager();

            $Projects = $this->getDoctrine()->getManager()
                    ->getRepository('ProjectBundle:Project')
                    ->findByAuthor($user->getUsername());
		
		/* Upload photo profil */
            
        $form = $this->createForm(new IdentityPictureType(), $user);

        if ($this->getRequest()->getMethod() === 'POST') {
            $form->bind($this->getRequest());
            if ($form->isValid()) {
                $em = $this->getDoctrine()->getEntityManager();
                
                $user->uploadProfilePicture();
                
                $em->persist($user);
                $em->flush();

                $this->redirect($this->generateUrl('homepage'));
			}
		}
    
        return $this->render('UserBundle:Default:show.html.twig', array('user' => $user, 'id' => $user->getId(), 'Projects' => $Projects, 'form' => $form->createView()));
    }

}

src/UserBundle/Controller/RegistrationController.php
<?php

namespace UserBundle\Controller;

use FOS\UserBundle\Controller\RegistrationController as BaseController;
use FOS\UserBundle\FOSUserEvents;
use FOS\UserBundle\Event\FormEvent;
use FOS\UserBundle\Event\GetResponseUserEvent;
use FOS\UserBundle\Event\FilterUserResponseEvent;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use FOS\UserBundle\Model\UserInterface;

class RegistrationController extends BaseController
{
	public function registerAction(Request $request)
    {
		if ($this->get('security.context')->isGranted('IS_AUTHENTICATED_FULLY', 'IS_AUTHENTICATED_REMEMBERED'))
		{
			return $this->redirect($this->generateUrl('homepage'));
		}
		
        /** @var $formFactory \FOS\UserBundle\Form\Factory\FactoryInterface */
        $formFactory = $this->get('fos_user.registration.form.factory');
        /** @var $userManager \FOS\UserBundle\Model\UserManagerInterface */
        $userManager = $this->get('fos_user.user_manager');
        /** @var $dispatcher \Symfony\Component\EventDispatcher\EventDispatcherInterface */
        $dispatcher = $this->get('event_dispatcher');

        $user = $userManager->createUser();
        $user->setEnabled(true);

        $event = new GetResponseUserEvent($user, $request);
        $dispatcher->dispatch(FOSUserEvents::REGISTRATION_INITIALIZE, $event);

        if (null !== $event->getResponse()) {
            return $event->getResponse();
        }

        $form = $formFactory->createForm();
        $form->setData($user);

        $form->handleRequest($request);

        if ($form->isValid()) {
            $event = new FormEvent($form, $request);
            $dispatcher->dispatch(FOSUserEvents::REGISTRATION_SUCCESS, $event);

            $userManager->updateUser($user);

            if (null === $response = $event->getResponse()) {
                $url = $this->generateUrl('fos_user_registration_confirmed');
                $response = new RedirectResponse($url);
            }

            $dispatcher->dispatch(FOSUserEvents::REGISTRATION_COMPLETED, new FilterUserResponseEvent($user, $request, $response));

            return $response;
        }

        return $this->render('FOSUserBundle:Registration:register.html.twig', array(
            'form' => $form->createView(),
        ));
	}
}

src/UserBundle/Controller/SecurityController.php
<?php

namespace UserBundle\Controller;

use FOS\UserBundle\Controller\SecurityController as BaseController;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\SecurityContextInterface;
use Symfony\Component\Security\Core\Exception\AuthenticationException;

class SecurityController extends BaseController
{
	protected function renderLogin(array $data)
    {
		if ($this->get('security.context')->isGranted('IS_AUTHENTICATED_FULLY', 'IS_AUTHENTICATED_REMEMBERED'))
		{
			return $this->redirect($this->generateUrl('homepage'));
		}
		
		return $this->render('FOSUserBundle:Security:login.html.twig', $data);
	}
}

src/UserBundle/Tests/Controller/DefaultControllerTest.php
<?php

namespace UserBundle\Tests\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class DefaultControllerTest extends WebTestCase
{
    public function testIndex()
    {
        $client = static::createClient();

        $crawler = $client->request('GET', '/hello/Fabien');

        $this->assertTrue($crawler->filter('html:contains("Hello Fabien")')->count() > 0);
    }
}

src/UserBundle/Resources/views/ChangePassword/changePassword_content.html.twig
<div class="container">
	<div class="col-md-offset-2 col-md-8 log-theme">
		<h2>Changer votre mot de passe</h2>
		
		<div class="col-md-offset-1 col-md-10">
			{{ form_start(form, { 'attr': {'class': ''} })  }}
				<div class="form-group">
					{{ form_label(form.current_password, "Mot de passe actuel") }}
					{{ form_widget(form.current_password,{'attr': {'class': 'form-control'}}) }}
					{{ form_errors(form.current_password) }}
				</div>
				
				<div class="form-group">
					{{ form_label(form.plainPassword.first, "Nouveau mot de passe") }}
					{{ form_widget(form.plainPassword.first,{'attr': {'class': 'form-control'}}) }}
					{{ form_errors(form.plainPassword.first) }}
				</div>
				
				<div class="form-group">
					{{ form_label(form.plainPassword.second, "Confirmer le nouveau mot de passe") }}
					{{ form_widget(form.plainPassword.second,{'attr': {'class': 'form-control'}}) }}
					{{ form_errors(form.plainPassword.second) }}
				</div>
				
				<button type="submit" class="btn btn-success col-md-offset-5">Soumettre</button>
			{{ form_end(form) }}
		</div>
	</div>
</div>

src/UserBundle/Resources/views/Default/show.html.twig
{% extends "::base.html.twig" %}

	{% block body %}

		<div class="col-md-offset-1 col-md-10 margin-top-prof">
				<div class="row featurette">
			        <div class="col-md-7 col-md-push-5">

				          <h2 class="featurette-heading text-center">{{user.username}}</h2>
				          <hr>
						<div class="col-md-3"><h3>
							{% set i = 0 %}
								{% for Project in Projects %}
									{% set i = i + 1 %}
								{% endfor %}

								{{ i }} Projets Lancés
						</h3></div>
						<div class="col-md-3"><h3>30 Projets Pushed</h3></div>
						{% if user.id == id %}
							<div class="col-md-3"><button type="button" class="btn btn-default btn-sm pad-btn-prof" data-toggle="modal" data-target="#avatar"><span class="glyphicon glyphicon-picture" aria-hidden="true"></span> Changer d'avatar</a></div>
						{% endif %}
						<div class="col-md-3"><a href="" type="button" class="btn btn-default btn-sm pad-btn-prof"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Contacter</a></div>
						
						<div class="modal fade" id="avatar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
						  <div class="modal-dialog">
							<div class="modal-content">
							  <div class="modal-header">
								<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
								<h4 class="modal-title" id="myModalLabel">Changer votre photo de profil</h4>
							  </div>
							  <div class="modal-body">
								<form action="#" method="post" {{ form_enctype(form) }}>
									{{ form_widget(form) }}

							  </div>
							  <div class="modal-footer">
								<button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
								<button type="submit" class="btn btn-primary">Valider</button>
								</form>
							  </div>
							</div>
						  </div>
						</div>
						
						<div class="col-md-12 margin-tab-prof">
							<hr>
							<div class="bs-example" data-example-id="striped-table">
							    <div class="table-responsive padd-tab-my">
							      <table class="table">
							        <thead>
							          <tr>
							            <th></th>
							            <th>Titre</th>
							            <th>Jours restants</th>
							            <th>Avancement</th>

							        </thead>
							        <tbody>

						        	{% for key,Project in Projects %}

						        		{% if Project.active != 0 %}
									
								        <tr>
									      

							          
							            <th>{{key+1}}</th>



							            <td>
							            	<a href="{{ path('project_show', {'id': Project.id}) }}">{{Project.title}}</a>							
							            </td>
										


							            <td>
							            	{% if Project.endDate | date('U') >= date().timestamp %}
							            	{{ (Project.endDate | date('U') - date().timestamp ) | date('d') }} jours restants
							            	{% else %}
							            	Projet terminé le {{ Project.endDate | date('d-m-Y') }}
							            	{% endif %}
							            </td>
							            <td>
							            	<div class="progress bar-prog-index margin-bar-prof">
						                                {% set integer = Project.amountWon / Project.amountRequested * 100 %}
						                                <div class="progress-bar" role="progressbar" aria-valuenow="{{integer}}" aria-valuemin="0" aria-valuemax="100" style="width:{{integer}}%;">
						                                  {{ integer | number_format(0) }}%
						                                </div>
						                    </div>
						                </td>
								            

										
							          </tr>
							            	


											{% endif %}
									{% endfor %} 

							        </tbody>
							      </table>
							    </div>
							  </div>
						</div>



			        </div>
			        <div class="col-md-5 col-md-pull-7">
						{% if user.pictureName == null %}
							<img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="500x500" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNTAwIiBoZWlnaHQ9IjUwMCIgdmlld0JveD0iMCAwIDUwMCA1MDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjxkZWZzLz48cmVjdCB3aWR0aD0iNTAwIiBoZWlnaHQ9IjUwMCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjE5MC4zMDQ2ODc1IiB5PSIyNTAiIHN0eWxlPSJmaWxsOiNBQUFBQUE7Zm9udC13ZWlnaHQ6Ym9sZDtmb250LWZhbWlseTpBcmlhbCwgSGVsdmV0aWNhLCBPcGVuIFNhbnMsIHNhbnMtc2VyaWYsIG1vbm9zcGFjZTtmb250LXNpemU6MjNwdDtkb21pbmFudC1iYXNlbGluZTpjZW50cmFsIj41MDB4NTAwPC90ZXh0PjwvZz48L3N2Zz4=" data-holder-rendered="true">
						
						
						{% else %}
							<img class="featurette-image img-responsive center-block" alt="500x500" src="{{ asset(user.webPath) }}" data-holder-rendered="true">
						{% endif %}
					  
			        </div>



			      </div>
		</div>


	{% endblock %}

src/UserBundle/Resources/views/Parameters/param.html.twig
	{# src/ProjectBundle/Resources/views/Project/show.html.twig #}
{% extends "::base.html.twig" %}

	
				{% block body %}
					<div class="container">
						<div class="col-md-offset-2 col-md-8 log-theme">
							<h2>Paramètres</h2>

								<div class="col-md-offset-1 col-md-10">
								
									<div class="form-group">
									    <label for="username">Nom d'utilisateur</label>
									    <input type="text" class="form-control" id="username" placeholder="Jane Doe">
									</div>
									<div class="form-group">
									    <label for="mail">Adresse mail</label>
									    <input type="text" class="form-control" id="mail" placeholder="d.jane@gmail.com">
									</div>

									<div class="form-group">
									    <label for="password">Nouveau mot de passe</label>
									    <input type="text" class="form-control" id="password" placeholder="Nouveau mot de passe">
									</div>

									<div class="form-group">
									    <label for="passwordConfirm">Confirmation mot de passe</label>
									    <input type="text" class="form-control" id="passwordConfirm" placeholder="Confirmer le nouveau mot de passe">
									</div>
								
									
									<button class="btn btn-primary">Modifier</button>
								</div>
		</div>


		

	</div>
	{% endblock %}

	

src/UserBundle/Resources/views/Resetting/checkEmail.html.twig
{% extends "FOSUserBundle::layout.html.twig" %}

{% trans_default_domain 'FOSUserBundle' %}

{% block fos_user_content %}
<div style="padding-top:5%;padding-bottom:5%;margin-top:5%;margin-bottom:5%;">
<h2 style="text-align: center;">Checkez votre boîte mail</h2></br>
<p style="text-align: center;">
{{ 'resetting.check_email'|trans({'%email%': email}) }}
</p>
</br></div>
{% endblock %}

src/UserBundle/Resources/views/Resetting/email.txt.twig
{% trans_default_domain 'FOSUserBundle' %}
{% block subject %}
{% autoescape false %}
{{ 'resetting.email.subject'|trans }}
{% endautoescape %}
{% endblock %}
{% block body_text %}
{% autoescape false %}
{{ 'resetting.email.message'|trans({'%username%': user.username, '%confirmationUrl%': confirmationUrl}) }}
{% endautoescape %}
{% endblock %}
{% block body_html %}{% endblock %}

src/UserBundle/Resources/views/Resetting/passwordAlreadyRequested.html.twig
{% extends "FOSUserBundle::layout.html.twig" %}

{% trans_default_domain 'FOSUserBundle' %}

{% block fos_user_content %}
<p>{{ 'resetting.password_already_requested'|trans }}</p>
{% endblock fos_user_content %}

src/UserBundle/Resources/views/Resetting/request.html.twig
{% extends "FOSUserBundle::layout.html.twig" %}

{% block fos_user_content %}
{% include "FOSUserBundle:Resetting:request_content.html.twig" %}
{% endblock fos_user_content %}

src/UserBundle/Resources/views/Resetting/request_content.html.twig
{% trans_default_domain 'FOSUserBundle' %}
	
	</br>
	<br>
	</br>
	<div class="col-md-4"></div>
	<div class="col-md-4 log-theme" style="padding-top:2.2%;padding-bottom:3.5%;margin-bottom:3%;">
        <h2 style="text-align:center;">Récupération du mot de passe</h2>
		
		</br>
		
		<div class="col-md-offset-1 col-md-10">
			<form action="{{ path('fos_user_resetting_send_email') }}" method="POST" class="fos_user_resetting_request">

				<div class="form-group">
					<div>
						{% if invalid_username is defined %}
							<p>{{ 'resetting.request.invalid_username'|trans({'%username%': invalid_username}) }}</p>
						{% endif %}
						<label for="username">{{ 'resetting.request.username'|trans }}</label>
						<input type="text" id="username" class="form-control" name="username" placeholder="Nom d'utilisateur ou mail" required="required" />
					</div>
					</br>
					<div class="clearfix"></div>
					
					<div class="clearfix"></div>
					
						<input type="submit" class="btn btn-success col-md-8 btn-block" value="{{ 'resetting.request.submit'|trans }}" />
					
				</div>
					
					
					
			</form>
		</div>
	</div>
	<br>

src/UserBundle/Resources/views/Resetting/reset.html.twig
{% extends "FOSUserBundle::layout.html.twig" %}

{% block fos_user_content %}
{% include "FOSUserBundle:Resetting:reset_content.html.twig" %}
{% endblock fos_user_content %}

src/UserBundle/Resources/views/Resetting/reset_content.html.twig
{% trans_default_domain 'FOSUserBundle' %}
<br>
<br>
<br>
<div class="col-md-4"></div>
<div class="col-md-4 log-theme" style="padding-top:2.2%;padding-bottom:3.5%;margin-bottom:2.5%;">
<h2>Nouveau mot de passe</h2>
	<div class="col-md-offset-1 col-md-10">
		<div  class="form-group">
		<form action="{{ path('fos_user_resetting_reset', {'token': token}) }}" {{ form_enctype(form) }} method="POST" class="fos_user_resetting_reset">
			
				{{ form_widget(form) }}
				</br>
				<div>
					<input type="submit" class="btn btn-success col-md-8 btn-block" value="{{ 'resetting.reset.submit'|trans }}" />
				</div>
		</form>
		</div>
	</div>
</div>

src/UserBundle/Resources/views/Security/login.html.twig
{% extends "FOSUserBundle::layout.html.twig" %}

{% trans_default_domain 'FOSUserBundle' %}

{% block fos_user_content %}

    <div class="col-md-4"></div>
      <div class="col-md-4 log-theme">
        <h2>Connexion</h2>

        {% if error %}
            <div>{{ error.messageKey|trans(error.messageData, 'security') }}</div>
        {% endif %}
        
        
        <div class="col-md-offset-1 col-md-10">
            <form action="{{ path("fos_user_security_check") }}" method="post">
                <input type="hidden"  name="_csrf_token" value="{{ csrf_token }}" />


                <div class="form-group">
                    <label for="username">{{ 'security.login.username'|trans }}</label>
                    <input type="text" class="form-control" id="username" name="_username" value="{{ last_username }}" placeholder="Nom d'utilisateur" required="required" />
                
                    <div class="clearfix"></div>

                    <label for="password">{{ 'security.login.password'|trans }}</label>
                    <input type="password" class="form-control" id="password" name="_password" placeholder="Mot de passe" required="required" />

                    <div class="clearfix"></div> 

                    
                        <input type="checkbox" id="remember_me" name="_remember_me" value="on" />
                        <label for="remember_me">{{ 'security.login.remember_me'|trans }}</label>
                    

                    <div class="clearfix"></div>

                    
                     <input type="submit" class="btn btn-success col-md-5" id="_submit" name="_submit" value="{{ 'security.login.submit'|trans }}" />
                    
                    </form>
                    
            <a href="{{path('fos_user_resetting_request')}}"><input type="button" class="btn btn-warning col-md-offset-1 col-md-6" value="Mot de passe oublié"></a>
                    

                </div>
            
            <div class="clearfix"></div>
    
             <hr class="hr-colore">
                <span>
                  Pas encore de compte ? <a href="{{path('fos_user_registration_register')}}">Inscrivez-vous !</a>
                </span>

                <hr class="hr-colore">

          <a href="#" class="btn btn-primary btn-lg active margin-fb-btn" role="button">Connexion par Facebook</a>
        </div>

    </div>
{% endblock fos_user_content %}